### ISSUE TITLE
Wasp's Quincarrier

### ISSUE THREAD

**Issue by alehandrof** [zzorba/marvelsdb#86]
The Wasp hero pack includes a reprint of Quincarrier that's not listed in the database.

**Comment by Kamalisk** [comment]
the duplicates will be solved soon hopefully.

**Comment by Psymonjet** [comment]
Related to that. When you're looking a deck that includes Quincarrier and you have Wasp Hero Pack but not Black Widow it shows you the '?' meaning that you're missing this card. (For sure that's because when building the deck the creator references the BW card)
The issue should be fixed when working on the isue that @alehandrof mention but also keeping an eye on that could be good too :)
![image](https://user-images.githubusercontent.com/37331743/122690675-44862200-d22b-11eb-8216-e350dc285d9a.png)

**Comment by jordanweiler** [comment]
Looks like this has been fixed https://marvelcdb.com/card/13025 and this issue can be closed.
